### ISSUE TITLE
Segmentation Fault in Alpine 3.8

### ISSUE THREAD

**Issue by adamralph** [adamralph/minver#149]
Caused by https://github.com/libgit2/libgit2sharp/issues/1647

**Comment by adamralph** [comment]
Released in [2.0.0-alpha.1](https://www.nuget.org/packages/MinVer/2.0.0-alpha.1).

**Comment by adamralph** [comment]
@thefringeninja this problem should be fixed in MinVer 2.0.0-alpha.1. Would you like to give it a try using the Alpine image?

**Comment by ViceIce** [comment]
`git` is not available by default on `mcr.microsoft.com/dotnet/core/sdk:2.2.402-alpine`

**Comment by adamralph** [comment]
@ViceIce do you think you can work around that easily enough? E.g. by adding `apt-get install git` to the container set up?

@thefringeninja did you have to explicitly install git when you tested this on Alpine?

**Comment by ViceIce** [comment]
@adamralph I'm using [this](https://github.com/VisualOn/docker-images/blob/master/docker/dotnet-sdk/Dockerfile) `Dockerfile`

**Comment by adamralph** [comment]
Thanks for the info.

So it seems `apk add git` is enough to get MinVer 2 working.

Git is now listed in the [prerequisites](https://github.com/adamralph/minver#prerequisites) so I assume no further action is needed.
