### ISSUE TITLE
debug/detailed level message when MinVerMajorMinor is redundant

### ISSUE THREAD

**Issue by adamralph** [adamralph/minver#151]
`MinVerMajorMinor` is redundant when a tag is found with a higher version.

Kudos to @cameronfletcher for suggesting this.

**Comment by bording** [comment]
Can you explain the scenario a bit more? I'm not sure I follow what the problem would be here.

**Comment by adamralph** [comment]
@bording if `MinVerMajorMinor` is set to `1.0`, and a `1.1` tag is added, then `MinVerMajorMinor` is redundant, since the tag supersedes it.

**Comment by bording** [comment]
Why does that need to be a warning? We're expecting it to be superseded in that case. It was originally called something like "minimumMajorMinor".

I've been thinking of that value as the same as the GitVersion's `next-version` property, which sets the floor for the version but doesn't set the ceiling.

**Comment by adamralph** [comment]
I guess it doesn't have to be a _warning_, it could just be a message at the info/normal level.

I keep thinking about changing the name back to `MinVerMinimumMajorMinor` but then finding excuses not to. I just found that name so unwieldy, but I guess it would completely remove the need for any message saying it's redundant, because the redundancy in the presence of a later tag is implicit in the name.

It also would get rid of the lingering concern I have that people may think they _need_ to increase the value to the next major-minor before they start labelling with that major-minor. Perhaps I should just bite the bullet and rename it back again...

**Comment by adamralph** [comment]
> If you have full verbose logging on, I would expect to see something that indicates that it was used to set the minimum version, but then something else (a tag) caused the version to be higher.

Makes sense. I'll convert this issue to that.

**Comment by adamralph** [comment]
Also raised https://github.com/adamralph/minver/issues/153

**Comment by adamralph** [comment]
Released in [beta 2](https://www.nuget.org/packages/MinVer/1.0.0-beta.2).
