### ISSUE TITLE
Provide ability to provide a MaxVersion

### ISSUE THREAD

**Issue by bartelink** [adamralph/minver#200]
I have a case where _we're using the CLI_ to derive a version from the tags at the start of a build. We have various mechanisms that then unconditionally publish builds to myget.

The issue we encountered was that a mis-tagging (actually some intentional programatic tagging which we were unaware of) let to us publishing a clearly wrong version (v2.x instead of v4.x).

That's easily solved: https://github.com/adamralph/minver#can-i-bump-the-major-or-minor-version

However, it does raise a different concern - is there a way to prevent someone triggering a v14.x.x by mistyping a tag ?

The simplest thing that enters my head is to provide a counterpart entitled `MinVerMaximumMajorMinor` which is a `<= x` equivalent of the `MinVerMinimumMajorMinor` builtin (which AIUI has "only consider a tag if it's `>= x` ?

**Comment by bartelink** [comment]
[Closing because have a better answer](https://en.wikipedia.org/wiki/Mu_(negative))

**Comment by bartelink** [comment]
Better answer fo this context was to have a verbose tag prefix of th style `release-4.1.3` and use that to make ensure no crossover with other tags being used for various purposes

**Comment by adamralph** [comment]
@bartelink that sounds like a good solution.
