### ISSUE TITLE
Can I independently version multiple packages in a single repository?

### ISSUE THREAD

**Issue by shaynevanasperen** [adamralph/minver#203]
I tried using this package in one of my repositories that has a main package and and extension package. These packages version independently, so it's not practical to use `MinVer`. I'm just throwing this out there in case anyone has an idea for solving this nicely.

**Comment by adamralph** [comment]
Hey @shaynevanasperen. You can do this quite easily by using two tag prefixes. E.g. `main.1.0.0` and `ext.2.0.0`. In the main project you'd specifiy `<MinVerTagPrefix>main.</MinVerTagPrefix>` and in the extension project you'd specify `<MinVerTagPrefix>ext.</MinVerTagPrefix>`. Or you could leave out the tag prefix for the main project entirely and only use one for the extension project.

**Comment by adamralph** [comment]
@shaynevanasperen thanks for raising this question, I've added it to the [FAQ](https://github.com/adamralph/minver#can-i-version-multiple-projects-in-a-single-repo-independently)!

If you have more questions, please feel free to re-open, or open a new issue.
