### ISSUE TITLE
Suppress NU5105 in consuming projects

### ISSUE THREAD

**Issue by adamralph** [adamralph/minver#209]
E.g.

> C:\Program Files\dotnet\sdk\2.2.104\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(202,5): warning NU5105: The package version '2.0.5-alpha.0.9+build.0' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on legacy clients. Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter. This message can be ignored if the package is not intended for older clients.

**Comment by bording** [comment]
This should be as simple as adding `<NoWarn>$(NoWarn);NU5015</NoWarn>` to a `PropertyGroup` in MinVer.targets.

**Comment by adamralph** [comment]
@bording exactly what I had in mind. But given that 1.0.0 is now in RC, I've put it on the 1.1.0 milestone. 

That said, it can be merged into master now. Any further required 1.0.0 commits can go into a `release-1.0` branch.

**Comment by adamralph** [comment]
Released in [1.1.0-beta.1](https://www.nuget.org/packages/MinVer/1.1.0-beta.1).

**Comment by adamralph** [comment]
https://github.com/adamralph/minver/pull/210 has a typo: `NU5015` instead of `NU5105`.

**Comment by adamralph** [comment]
Released in [1.1.0-beta.2](https://www.nuget.org/packages/MinVer/1.1.0-beta.2).
