### ISSUE TITLE
Option to increment minor or major version instead of patch

### ISSUE THREAD

**Issue by adamralph** [adamralph/minver#212]
When the latest tag is an RTM, and is on an older commit, the patch version is incremented. E.g. if the latest tag is `1.0.0` at a height of 3 commits, the current commit version is `1.0.1-alpha.0.3`.

Some projects do not use the patch version, so it would make more sense for the version to be `1.1.0-alpha.0.3`. Some projects may even not use the minor version, which means the version should be `2.0.0-alpha.0.3`.

This could be configurable via a new option.

**Comment by enzian** [comment]
hey, need help on that?

**Comment by adamralph** [comment]
Hey @enzian, sure thing! I guess, from the user's perspective, this would result in a new property. Something like:

```xml
<MinVerAutoIncrement>major|minor|patch(default)</MinVerAutoIncrement>
```

I'm not wild about the name `MinVerAutoIncrement`. Any better idea? /cc @leastprivilege

**Comment by enzian** [comment]
I preliminarily introduced the `--increment-segment` option in the CLI, but I don't have a strong opinion about the naming either!

**Comment by adamralph** [comment]
@enzian thanks for the PR!

But also apologies, because I was not clear in my previous comment:

```xml
<MinVerAutoIncrement>major|minor|patch(default)</MinVerAutoIncrement>
```

I was using `|` to mean "or". That is, the default (implicit) value would be:

```xml
<MinVerAutoIncrement>patch</MinVerAutoIncrement>
```

And that could be changed to:

```xml
<MinVerAutoIncrement>minor</MinVerAutoIncrement>
```

or:

```xml
<MinVerAutoIncrement>major</MinVerAutoIncrement>
```

I can't think of a valid use case to auto-increment more than one part of the version.

**Comment by enzian** [comment]
@adamralph : I've seen (just once...) that a company did not release versions like 2.0.0. The first version they would release was 2.1.0 (for what reason is unclear to me...)! Should I switch to a single value?

**Comment by adamralph** [comment]
That sounds like a bizarre versioning scheme and not one I really want to encourage. 😉

I think, for now, let's stick to a single value for simplicity. We can always extend it to multiple values later, but I hope noone asks for that. 😉

**Comment by enzian** [comment]
@adamralph maybe it was  also a case of _over engineering is underrated_ ;-) I patched it!

**Comment by adamralph** [comment]
Released in [1.1.0-beta.1](https://www.nuget.org/packages/MinVer/1.1.0-beta.1).

@leastprivilege would you like to give it a try? Just add a property:

```xml
<MinVerAutoIncrement>minor</MinVerAutoIncrement>
```

**Comment by leastprivilege** [comment]
sorry - swamped right now...

**Comment by adamralph** [comment]
@leastprivilege FYI I just pushed [1.1.0-rc.1](https://www.nuget.org/packages/MinVer/1.1.0-rc.1).
