### ISSUE TITLE
Configurable default pre-release phase

### ISSUE THREAD

**Issue by adamralph** [adamralph/minver#246]
Historically, the default pre-release phase was hardcoded to "alpha". As stated in the [README](https://github.com/adamralph/minver#how-it-works), this resulted in a default version of `0.0.0-alpha.{height}` or a post-RTM version of `{major}.{minor}.{patch+1}-alpha.{height}`.

This feature introduces a new option for the default pre-release phase. For example, the option may be set to "preview":

- Using the MinVer package:
  ```xml
  <MinVerDefaultPreReleasePhase>preview<MinVerDefaultPreReleasePhase>
  ```
- Using the minver-cli package:
  ```bash
  minver --default-pre-release-phase preview
  ```

This will result in a default version of `0.0.0-preview.{height}` or a post-RTM version of `{major}.{minor}.{patch+1}-preview.{height}`. E.g. `1.0.1-preview.1`.

**Comment by adamralph** [comment]
@Selmirrrrr @fuzzzerd I've released this in [1.2.0-beta.1](https://www.nuget.org/packages/MinVer/1.2.0-beta.1) if you want to give it a try.

**Comment by Selmirrrrr** [comment]
@adamralph great ! I'll play with it tonight and update our projects using MinVer to this 1.2.0-beta.1 version.

**Comment by fuzzzerd** [comment]
@adamralph Seems to behave as advertised. Thanks for releasing it promptly. @Selmirrrrr thanks for implementing this.

**Comment by Selmirrrrr** [comment]
@adamralph everything seems working as expected 🔥
