### ISSUE TITLE
What does the zero after preview label symbolize

### ISSUE THREAD

**Issue by joacar** [adamralph/minver#324]
Hi

Starting of with says thanks to a great package! Now, to the question:

1. ~What does the zero after the {prerelease-label} symbolize?~ So I just realized and tested making a tag **with** the pre-release label I specified in props-file and the zero went away. Based on that I guess it's there to symbolize "unofficial" preview, i.e. just a commit made after a tag. It [compares](https://semvercompare.azurewebsites.net/?version=1.0.0-preview.0.2&version=1.0.0-preview.1&version=1.0.0-preview.2) nicely as the lesser of an intentional preview-tag.
1. Is it possible to customize the version suffix?
1. What is the reason for git commit height deviating from that calculated by GitInfo?
1. Is the calculated commit height available in MSBuild?

I asked this in [SO](https://stackoverflow.com/questions/60321978/customize-version-suffix-minver) which contains more details. When (if) I'll get answers here I'll transfer them to SO.

Found [this](https://github.com/adamralph/minver/issues/242) which touch question 1, but couldn't find any explanation for the zero.

Thanks

**Comment by adamralph** [comment]
@joacar thanks for asking your questions. [I've answered them in SO](https://stackoverflow.com/questions/60321978/customize-version-suffix-minver/60382255#60382255).
