### ISSUE TITLE
Versioning a Docker Image using MinVer CLI

### ISSUE THREAD

**Issue by RehanSaeed** [adamralph/minver#331]
I'm trying to version a docker image using the MinVer CLI. According to [the docs](https://github.com/adamralph/minver/tree/2f7678cd55d6f3d29435b454aafba974fdb298e0#can-i-use-minver-to-version-software-which-is-not-built-using-a-net-sdk-style-project), I need to run the CLI before I build the project and then take the version and put it in the `MINVERVERSIONOVERRIDE` environment variable.

However, if you change any of the default options in your `.csproj` file or `Directory.Build.props`:

- MinVerAutoIncrement
- MinVerBuildMetadata
- MinVerDefaultPreReleasePhase
- MinVerMinimumMajorMinor
- MinVerTagPrefix
- MinVerVerbosity
- MinVerVersionOverride

Running `dotnet minver` will ignore them and use the default options to generate a version. Perhaps it could take the working directory into consideration and read any options from `.csproj` or `Directory.Build.props` files that it finds.

**Comment by adamralph** [comment]
@RehanSaeed the CLI has all the same options available:

```
C:\code> minver -?
MinVer CLI 2.2.0+2dc05b013643525c8b4739df5581d727cf7d64f0

Usage: minver [options]

Options:
  -?|-h|--help                                    Show help information
  -a|--auto-increment <VERSION_PART>              major, minor, or patch (default)
  -b|--build-metadata <BUILD_METADATA>
  -d|--default-pre-release-phase <PHASE>          alpha (default), preview, etc.
  -m|--minimum-major-minor <MINIMUM_MAJOR_MINOR>  1.0, 1.1, 2.0, etc.
  -r|--repo <REPO>                                Working directory.
  -t|--tag-prefix <TAG_PREFIX>
  -v|--verbosity <VERBOSITY>                      e[rror], w[arn], i[nfo] (default), d[ebug], or t[race] (case insensitive)
```

You should set your options when you call the CLI, instead of in `.csproj` or `Directory.Build.props`.

**Comment by adamralph** [comment]
@RehanSaeed I'm closing this based on the assumption that the CLI options satisfy your needs. If you have any further questions, please chime in again, or raise a new issue.
