### ISSUE TITLE
[Question] How to retrieve the assembly information calculated by MinVer? (Azure DevOps)

### ISSUE THREAD

**Issue by bdelsaz** [adamralph/minver#333]
First of all, thank you for this great tool!

I am using MinVer in an Azure DevOps build pipeline to tag my assemblies. I would like to use the calculated tag to name the docker image which is created during that same build process.

I am installing MinVer as nuget package in all my assemblies, and I am using the MinVer command line tool in my build pipeline.

My question is: How can I retrieve the calculated version? With GitVersion you just say something like `GitVersion.SemVer`. The documentation speaks about 'MinVer properties' but I cannot access these from the command line tool.  Should I instead create a powershell script to retrieve this assembly information?

**Comment by adamralph** [comment]
@bdelsaz when you run the CLI tool, it prints the calculated version to `stdout`, and you can then do what you want with it. If you also have the regular MinVer package installed in .NET projects in the same repo, then remember to set the MINVERVERSIONOVERRIDE environment variable to the calculated version before building them, as described in the [related FAQ](https://github.com/adamralph/minver#can-i-use-minver-to-version-software-which-is-not-built-using-a-net-sdk-style-project).

**Comment by adamralph** [comment]
@bdelsaz I'm closing this on the assumption that you have the information you need. Otherwise, please chime in again or raise a new issue. Thank you.

**Comment by bdelsaz** [comment]
Thank you for the response, and apologies that I forgot to respond earlier! 
I have now a better understanding of how minver work. I indeed used the minver CLI in our Azure Devops pipeline.
