### ISSUE TITLE
Assembly attributes not written (or overwritten) using SDK 3.1.300

### ISSUE THREAD

**Issue by joacar** [adamralph/minver#343]
It works great if built with SDK < 3.1.300 but fails on 3.1.300.

## Version(s)

2.2.0

## To reproduce

There is a tag 2.1.3 and that value should be displayed at first run.

1. Run included console app
1. Change global.json to 3.1.300
1. Run included console app

[ConsoleApp2.zip](https://github.com/adamralph/minver/files/4678078/ConsoleApp2.zip)

## Expected behavior

See informational version 2.1.3 as calculated by MinVer

## Actual behaviour

Default 1.0.0

## Workarounds

Haven't find any. Tried to elaborate will target order but no luck.

## Additional context

Only seen this in 3.1.300

**Comment by bording** [comment]
@joacar See #344 for more details and the fix.

**Comment by joacar** [comment]
@bording Great job with a quick fix!

**Comment by adamralph** [comment]
@joacar thanks for raising this and for the detailed repro! Since this was caused by a breaking change in SDK 3.1.300, I'm not treating this as a bug in MinVer, so I'm withdrawing this issue in favour of https://github.com/adamralph/minver/pull/347.
