### ISSUE TITLE
Beta tag special treatment 

### ISSUE THREAD

**Issue by maxcherednik** [adamralph/minver#351]
We have a situation like this:
![image](https://user-images.githubusercontent.com/4208513/83842233-b2d07300-a702-11ea-8ec5-5cd3a604e87a.png)

where we had commit on a hotfix branch tagged as 8.2.2-beta.1 and then merged into develop.

for develop we run this: 
`dotnet minver -a minor -d unstable`

**Expected version:** 
`8.3.0-unstable.1`

**Actual result:**
`8.2.2-beta.1.1`

Both -a option and -d options are ignore.

**Comment by adamralph** [comment]
Hi @maxcherednik, thanks for raising this question.

I'm afraid you are misunderstanding how MinVer works. MinVer doesn't care about branches. The version is determined by the latest version tag found in the history. If the latest version tag found is `8.2.2-beta.1` at a height of one commit, then the expected version is indeed `8.2.2-beta.1.1`. Full details are available in _[How it works](https://github.com/adamralph/minver#how-it-works)_.

The `-a` and `-d` options are only used when the latest version tag is RTM (not pre-release), in which case MinVer has to calculate a pre-release version for the current commit. The `-a` option controls [how the version is incremented](https://github.com/adamralph/minver#can-i-auto-increment-the-minor-or-major-version-after-an-rtm-tag-instead-of-the-patch-version), and the `-d` option controls [the default pre-release phase](https://github.com/adamralph/minver#can-i-change-the-default-pre-release-phase-from-alpha-to-something-else).

If you want to use a specific branch (`master`, `develop` or anything else) to embark on developing a specific version range then you have three options:

- Wait until the first time you actually want to release something from that branch, in which case you will tag some commit with the version you are releasing, e.g. `8.3.0-unstable.1`.
- [Bump the version range](https://github.com/adamralph/minver#can-i-bump-the-major-or-minor-version) using `MinVerMinimumMajorMinor` (or `-m` on the command line).
- Tag the first commit on that branch with a sentinal pre-release version of zero. I.e. not a version you would actually release, e.g. `8.3.0-unstable.0`.

BTW - if `unstable` is your preferred default pre-release phase then you should continue using `-d unstable` or `<MinVerDefaultPreReleasePhase>unstable</MinVerDefaultPreReleasePhase>`, but bear in mind that it will sort alphanumerically _after_ both `alpha` and `beta`. Effectively, a default pre-release phase of `unstable` is incompatible with the `alpha` and `beta` pre-release naming scheme. Your default pre-release phase should really sort alphanumerically _before_ any other pre-release phases you intend to use.

**Comment by maxcherednik** [comment]
>I'm afraid you are misunderstanding how MinVer works. MinVer doesn't care about branches. The version is determined by the latest version tag found in the history. If the latest version tag found is 8.2.2-beta.1 at a height of one commit, then the expected version is indeed 8.2.2-beta.1.1. Full details are available in How it works.

I have read the docs. I knew that branches are not important. I just missed that part, that non RTM tags are special case.

Even though I find it a bit counter-intuitive that I can't override this behavior. I guess, logic is ok, but the override options should have the power to change the behavior - it gives more flexibility without sacrificing the purpose of the MinVer.

**Comment by adamralph** [comment]
The override you want is already there:

```
minver -m 8.3 -d unstable
```

**Comment by maxcherednik** [comment]
How do I know it is 8.3? We don't want to do manual tagging or anything. It defeats the purpose.

If I go into details, the script always runs against the repo, it is branches, pr's, hot-fixes, releases, etc
The main moto of the MinVer - `branches do not matter`, they actually still do. It is just the not a problem of the MinVer. It kinda says you are controlling what version you gonna get.
Default on any branch you run `minver` command - it bumps the patch part and adds `alpha` prefix.
You don't like the patch part - then run `minver -a minor`
You don't like the suffix part - then run `minver -d whateversuffix`

So the convention we have is this: 
if it is a develop branch, there must be a previous release tag somewhere in the past. Does not matter RTM or pre-release. 
So any time we run the script on `develop`, it is a generic command:
`minver -a minor -d unstable`

So it seems to me(I might not see the whole picture or missing something), that the usage of the MinVer could be like this.
1. Always run `minver` - it will do the default calculation logic(the one we have right now).
2. If you you don't like the default - then `minver -a minor` or `minver -a major`

In this order it keeps the current logic plus, preserves the simplicity and gives the options to override the behaviour.

**Comment by adamralph** [comment]
> How do I know it is 8.3?

How should MinVer know? If the latest tag MinVer finds is `8.2.2-beta.1` how should it know whether the current commit is another version in the 8.2.2 range or the 8.3.0 range?

> We don't want to do manual tagging or anything.

This is the entire premise of MinVer. The first thing you do before releasing is tag the commit. You then build it, MinVer uses the version from the tag, and you release.

**Comment by maxcherednik** [comment]
>How should MinVer know? 

It does not and should not. The whole idea of MinVer is just cool.
If it finds any tag, then it does what it does now. `8.2.2-beta.1`, then it must be `8.2.2-beta.1.1`.
But I(not the MinVer) know that we are on `develop` and whatever the tags they are in the past, they all refer to the support branches. And the knowledge of the current branch(develop) tells me that whatever the version it was before it is always `minver -a minor`. In case of `8.2.2-beta.1` tag it is going to be `8.3.0-apha.0.1`. In case of `8.10.2-rc.6` tag it is still going to be `8.11.0-apha.0.1`

See my point?

**Comment by adamralph** [comment]
I do see your point, but MinVer does not, and likely never will, do branch-based versioning. If you need branch based versioning, you may want to look at something like GitVersion. IMO branch based versioning is a can of worms and is the main reason GitVersion suffers from so much complexity. In turn, that is the main reason I wrote MinVer.

As long as you are using MinVer, you will have to use one of the methods I mentioned above:

> 1. Wait until the first time you actually want to release something from that branch, in which case you will tag some commit with the version you are releasing, e.g. `8.3.0-unstable.1`.
> 1. [Bump the version range](https://github.com/adamralph/minver#can-i-bump-the-major-or-minor-version) using `MinVerMinimumMajorMinor` (or `-m` on the command line).
> 1. Tag the first commit on that branch with a sentinal pre-release version of zero. I.e. not a version you would actually release, e.g. `8.3.0-unstable.0`.

FWIW, I use method 1 in my projects. I have no general use for the artifacts that are produced from untagged commits, so I don't care that the mainline branch is producing `8.2.2-{x}` versions until I tag a commit on that branch with `8.3.0{y}`.

I guess what you really need is a MinVer option which forces a version increment even when the previous tag is a pre-release. If that existed, you would still have to work out the branch yourself and pass that option conditionally, based on the branch. I guess that option could be added, but right now I'm not really convinced that the benefit over method 1 above outweighs the cost of adding it. It would likely remain a niche use case, and it could be quite error prone since it would effectively place the burden of branch based versioning on the consumer.

**Comment by maxcherednik** [comment]
> but MinVer does not, and likely never will, do branch-based versioning. 

I am not asking for it. I like the way it is. When the tool is not handling the branches, someone still does. It is outside of the MinVer.

>If you need branch based versioning, you may want to look at something like GitVersion. IMO branch based versioning is a can of worms and is the main reason GitVersion suffers from so much complexity. In turn, that is the main reason I wrote MinVer.

Exactly the reason we are trying to go away from the GitVersion. MinVer - fast, predictable, _overridable_(this is not completely true now)


> I guess what you really need is a MinVer option which forces a version increment even when the previous tag is a pre-release. 

Exactly what we need! And what I propose does not seem like a major change.


**Current behavior:**
1. Default - bumps minor, suffix - alpha.
1. Override flags give me the way to configure which part to bump and the suffix
1. If there is a pre-release tag, bumps nothing but height, suffix - the same as the tag
 
**Proposed behavior(nearly the same):**
1. Default - bumps minor, suffix - alpha.
1. If there is a pre-release tag, bumps nothing but height, suffix - the same as the tag
1. Override flags give me maximum configurability and overridability.

The proposed behavior truly covers all possible branching strategies. Those you mention in the documentation: gitflow, githubflow, whatever. Because the proposed behavior is not about branches.

**Comment by adamralph** [comment]
@maxcherednik before embarking on a new feature, I'd like to explore the use case a little. Why is it important to you that your `develop` branch starts producing `8.3.0-{x}` versions before the next tag?

**Comment by maxcherednik** [comment]
@adamralph of course. We need to validate the idea.

![image](https://user-images.githubusercontent.com/4208513/83942926-4899fa00-a7f8-11ea-85da-c739f12bf338.png)

**Comment by maxcherednik** [comment]
>Tag the first commit on that branch with a sentinal pre-release version of zero. I.e. not a version you would actually release, e.g. 8.3.0-unstable.0.

@adamralph was reading a bit of a code. The option seems logical and makes sense. So basically when we create a release branch, we can put this sentinel tag on develop and it will continue counting from there, no matter all the other supporting tags on all the branches. All those tags have lower version and they never override the sentinel tag.

**Comment by adamralph** [comment]
@maxcherednik that's correct. This is effectively your way of telling MinVer that `develop` has moved on to the 8.3.0 range. Does this mean your use case is covered?

**Comment by maxcherednik** [comment]
Seems like it. Thank you for your help.

Maybe a good idea - to add this example to a documentation or something.

**Comment by adamralph** [comment]
> Seems like it. Thank you for your help.

You're welcome. Thanks for discussing your use case.

> Maybe a good idea - to add this example to the documentation or something.

It's already in the [FAQ](https://github.com/adamralph/minver#can-i-bump-the-major-or-minor-version).

**Comment by adamralph** [comment]
Sorry, my mistake: it's not listed as an option in that FAQ. Perhaps it should be added as you suggest.

**Comment by maxcherednik** [comment]
Found tiny issue with the sentinel tag approach.
I can't name the pull-requests to this branch.
Before it was something like this `minver -d prId`

In the [documentation](https://github.com/adamralph/minver#can-i-use-the-version-calculated-by-minver-for-other-purposes): it is possible to compose the version, but with the minver-cli there is no such option.

**Comment by adamralph** [comment]
@maxcherednik to do that, you would have to first decompose the version. This may be done reliably because the version format is deterministic. I don't know what language you are using to write your build script, but in C# it's quite easy:

```c#
var metaSplit = version.Split('+', 2);
var preSplit = metaSplit[0].Split('-', 2);
var (rtm, preRelease, buildMetadata) =
    (preSplit[0], preSplit.ElementAtOrDefault(1), metaSplit.ElementAtOrDefault(1));
```

**Comment by adamralph** [comment]
@maxcherednik FYI I raised a PR to add the tagging option to the FAQ — https://github.com/adamralph/minver/pull/352. Thanks for the suggestion.
