### ISSUE TITLE
Is there a possibility of creating duplicate version numbers?

### ISSUE THREAD

**Issue by JimBobSquarePants** [adamralph/minver#356]
I may be misinterpreting the documentation here...

By my understanding I can replace the normal prerelease part of a version number by following the below instructions.
https://github.com/adamralph/minver#can-i-change-the-default-pre-release-phase-from-alpha-to-something-else

### Can I change the default pre-release phase from "alpha" to something else?
Yes! Specify the default pre-release phase with `MinVerDefaultPreReleasePhase`. For example, if you prefer to name your pre-releases as "preview":

``` xml
<PropertyGroup>
  <MinVerDefaultPreReleasePhase>preview</MinVerDefaultPreReleasePhase>
</PropertyGroup>
```

This will result in a post-RTM version of` {major}.{minor}.{patch+1}-preview.{height}`, e.g. `1.0.1-preview.1`.

So that being the case I'm making an assumption here that constant prefix will replace all prerelease portions from future preleases states.

For example. 

Given a prerelease tag `1.0.0-beta.2` would subsequent builds generate `1.0.0-beta.2.{height}` or `1.0.0-preview.{height}` or `1.0.0-preview.2.{height}`?

Now assuming that the versioning strategy was either of the latter two cases I see a distinct possibility that versioning could be repeated leading to a lack of upgrade path for unstable or nightly builds since `height` is a count of commits since the tag by my understanding.

If I follow the beta release with another prerelease tag `1.0.0-rc.2` that would generate either `1.0.0-preview.{height}` or `1.0.0-preview.2.{height}` which, since commit height values would be reset, leads to duplication. 

Am I missing something?

**Comment by adamralph** [comment]
@JimBobSquarePants thanks for raising this.

`MinVerDefaultPreReleasePhase` is only used when the latest version tag is RTM. In that case, MinVer needs to version the current commit as a pre-release for the _next_ version, and it uses the default pre-release phase to do so. From [_How it works_](MinVerDefaultPreReleasePhase):

> - If the current commit _does not_ have a version tag:
> ...
>   - The commit history is searched for the latest commit with a version tag.
> ...
>     - If a commit with a version tag is found:
> ....
>       - If the version is RTM (not pre-release):
> ...
        - Default pre-release identifiers are added. The default pre-release phase is "alpha", but this [can be customised](#can-i-change-the-default-pre-release-phase-from-alpha-to-something-else).

When you tag a commit, that tag is used as-is. Again, this in _How it works_. If something in _How it works_ is not clear, please let me know.

**Comment by JimBobSquarePants** [comment]
Oops I misread that bit. Makes perfect sense, thanks!
