### ISSUE TITLE
Problem with subtree

### ISSUE THREAD

**Issue by karlika** [adamralph/minver#363]
We have a project where we added sources from another repo using git subtree:
`git subtree add –-prefix src/mainframe https://[REPOPATH]/mainframe.git master --squash`

If I now run the minver CLI on this repo it ignores a whole lot of commits and computes a depth which is too low.
Actually in the current run (3) it was lower than the previous run before the last subtree change (4).

I'm not a 100% sure, how my colleagues did the subtree update, but it looks like they manually removed the folder where the subtree was added, committed and did the `git subtree add` again.

Is there any way we can get a valid depth with the subtree?

[minver_trace_log.txt](https://github.com/adamralph/minver/files/4995909/minver_trace_log.txt)

**Comment by adamralph** [comment]
Hi @karlika, thanks for raising this.

I'm afraid I have no idea about subtrees and how they work. I've never used one. I would have no idea where to start in diagnosing the problem.

As you can see from the log you attached, MinVer simples relies on the output from the various git commands it is running. If you can figure out what is required to support subtrees then I may accept a pull request to add the feature, if it does not introduce too much complexity.
