### ISSUE TITLE
Incorrect depth after commit from a new repo

### ISSUE THREAD

**Issue by karlika** [adamralph/minver#370]
## Version(s)

2.3.0

## To reproduce

1. Create a new repo A locally
2. Add remote in A to an existing repo B on the server
3. Do some local changes
4. Commit and push to remote repo B
5. Clone repo B locally and run minver

## Expected behavior

The commit depth should in crease at least by one.

## Actual behaviour

The original root commit is now ignored and the root commit from the new repo is taken as base for counting the depth.
In most cases this means that the depth actually decreases.

## Workarounds

None known

## Additional context

Would it be possible to ignore all but the root commit with the highest depth?
This way at least there should never be a decrease in the depth (if not actually changing the commit history)

**Comment by adamralph** [comment]
@karlika thanks for raising this.

I'm not entirely sure I understand the problem. If you clone repo B and build, MinVer only has whatever is in B to work with. The existence of repo A is irrelevant.

**Comment by karlika** [comment]
@adamralph 
Since we pushed all the commits from A to remote B, B will also contain those.
Unfortunately also the initial commit from A which does not have a parent and is thus considered a 'root' commit.

**Comment by adamralph** [comment]
@karlika do you have a public repo which demonstrates the problem?

**Comment by karlika** [comment]
@adamralph 2.3.1-beta.2 with your changes from #377 also fixes this issue
