### ISSUE TITLE
Read MINVERBUILDMETADATA environment variable in minver-cli

### ISSUE THREAD

**Issue by augustoproiete** [adamralph/minver#423]
## Use case(s)

The documentation shows a useful [example](https://github.com/adamralph/minver#can-i-include-build-metadata-in-the-version) of configuring `MINVERBUILDMETADATA` with the build number generated by the build server:

`appveyor.yml`:

```yaml
environment:
  MINVERBUILDMETADATA: build.%APPVEYOR_BUILD_NUMBER%
```

It would be convenient if `minver-cli` could leverage this environment variable to define a default value for the build metadata, which would allow devs to define a default `MINVERBUILDMETADATA` env. variable across projects/build configurations on their build server.

## Description

If the user provided a value through the command-line via `--build-metadata` MinVer would continue to use that as it is today.

However, if the user did not provide a value through `--build-metadata`, MinVer would try to use the value of the environment variable `MINVERBUILDMETADATA` if present.

## Alternatives

Of course, using the environment variable in the command line works:

```powershell
minver --build-metadata "%MINVERBUILDMETADATA%"
```

As long as the environment variable is defined, otherwise you get a funny version `1.0.0+%MINVERBUILDMETADATA%`, which is technically correct.

**Comment by adamralph** [comment]
hi @augustoproiete, thanks for raising this. It seems reasonable. However, if we are to do this, should we extend it to all the options?

```bash
  -a|--auto-increment <VERSION_PART>              major, minor, or patch (default)
  -b|--build-metadata <BUILD_METADATA>
  -d|--default-pre-release-phase <PHASE>          alpha (default), preview, etc.
  -m|--minimum-major-minor <MINIMUM_MAJOR_MINOR>  1.0, 1.1, 2.0, etc.
  -t|--tag-prefix <TAG_PREFIX>
  -v|--verbosity <VERBOSITY>                      e[rror], w[arn], i[nfo] (default), d[ebug], or t[race] (case insensitive)
```

Note that I left out this one, since, in retrospect, this should probably be an argument, rather than an option:

```bash
  -r|--repo <REPO>                                Working directory.
```

**Comment by augustoproiete** [comment]
@adamralph Yes, I think it would make sense to extend to the other options for consistency.

At the moment [all the options that can be specified for MSBuild](https://github.com/adamralph/minver#options) can be environment variables, so minver-cli could support the exact same variables (as fallback if not provided via command-line):

- `MINVERAUTOINCREMENT`
- `MINVERBUILDMETADATA`
- `MINVERDEFAULTPRERELEASEPHASE`
- `MINVERMINIMUMMAJORMINOR`
- `MINVERSKIP`
- `MINVERTAGPREFIX`
- `MINVERVERBOSITY`
- `MINVERVERSIONOVERRIDE`

**Comment by adamralph** [comment]
@augustoproiete 👍 that makes sense to me.

**Comment by adamralph** [comment]
Thanks again for raising this @augustoproiete. FYI I am closing this in favour of the more general https://github.com/adamralph/minver/issues/450 which covers all options (except for `MinVerSkip`).
