### ISSUE TITLE
Using MinVer in a Docker build

### ISSUE THREAD

**Issue by stevehansen** [adamralph/minver#438]
Not sure if this should be flagged as a bug but I couldn't find anything directly in the documentation.

We added MinVer to our project with success when it builds locally. But our production deployment is using Azure DevOps based on a Dockerfile. Every image that is built contains the version 0.0.0-alpha.0. I'm assuming MinVer doesn't have access to the needed git data at that moment but I'm not sure what we'll need to add to get this working. We are using the default generated Dockerfile when you add Docker support to a project.

The build does confirm that it's missing the info:
```
MinVer : warning MINVER1001: '/src/Project' is not a valid working directory. Using default version 0.0.0-alpha.0. [/src/Project/Project.csproj]
```

Did anyone get this scenario working?

**Comment by bording** [comment]
This really isn't something unique to MinVer. You'd have similar problems with any sort of git-based versioning tool. They all require access to the git repo data to calculate the version.

For MinVer, the ways I could think of solving the issue:

- Add the .git folder to the docker image
- Run the MinVer command line tool outside of the image, and pass the appropriate environment variables into the docker image. See [this](https://github.com/adamralph/minver#can-i-use-minver-to-version-software-which-is-not-built-using-a-net-sdk-style-project) FAQ that talks about using the command line tool.

**Comment by stevehansen** [comment]
Thanks for pointing me to the correct solution, it seems the autogenerated files include .git in the .dockerignore file removing that part made everything work
