### ISSUE TITLE
Use environment variables in minver-cli

### ISSUE THREAD

**Issue by adamralph** [adamralph/minver#450]
_Thanks to @augustoproiete for raising #423 for `MinVerBuildMetadata`, which led to this more general enhancement._

The `MinVer` package accepts options as [environment variables](https://github.com/adamralph/minver#options). This is standard .NET SDK behaviour: all environment variables are propagated as MSBuild properties.

With this enhancement, the `minver-cli` package does the same thing.

There is one exception: `MinVerSkip`. This option effectively switches off the `MinVer` package, which means none of the output properties will be set, which means the SDK will use whatever version is set via a `Version` property, whether that is explicitly done for a project, or implicitly done by the SDK as a default value. There is no good equivalent for `minver-cli`. If the command line were "switched off", then the equivalent behaviour would be to return no value. If a user wants to "switch off" the `minver-cli` package, then they can observe `MinVerSkip` themselves and provide an alternate version string in that scenario.

**Comment by adamralph** [comment]
Released in [2.4.0-beta.1](https://www.nuget.org/packages/minver-cli/2.4.0-beta.1).

@augustoproiete please give it a try.

**Comment by augustoproiete** [comment]
Cheers @adamralph! I will take it for a spin!
