### ISSUE TITLE
Migrating from GitVersion

### ISSUE THREAD

**Issue by kieronlanning** [adamralph/minver#470]
I'm migrating away from GitVersion which I couldn't ever get quite stable, and trying to replicate something like a branching of `dev` ->  `main`  where dev is where all the work happens, and then main results in a build and a new version bump. 

Occasionally I might need to get a build from `dev` that is something like a preview or beta build.

My issue mainly revolves are trying to integration the CLI into my build pipeline, given I've already got tags representing previous versions.

Is there any guidance on initial setup like this using Azure DevOps? I'm finding that I need to manually tag a build to get the right version at the moment.

Currently the build YAML looks like this:

```
variables:
  MinVer: ''
.
.
.
- task: PowerShell@2
  displayName: 'Set MinVer Version'
  inputs:
    targetType: inline
    script: |
      $version = dotnet minver -v e
      echo "##vso[task.setvariable variable=MinVer]$version"
      Write-Host "Setting MinVer to '$version'"

- task: PowerShell@2
  displayName: 'Updating AssemblyInfo'
  inputs:
    targetType: filePath
    filePath: "build/scripts/build/update-version-info.ps1"
    arguments: "-newVersion $(MinVer) -filePath build/msbuild/Properties/AssemblyInfo_Versioning.cs"
.
.
.
- task: DotNetCoreCLI@2
  displayName: '.NET Core: Pack'
  condition: succeeded()
  inputs:
    command: custom
    custom: pack
    arguments: $(solutionFile) --nologo -c $(buildConfiguration) -v q -m --include-symbols --include-source --output $(build.artifactstagingdirectory)/dropartifacts/ /p:Version=$(MinVer) 
```

**Comment by adamralph** [comment]
hi @kieronlanning, unless you're doing something exotic, you should be able to remove all those tasks and just install the MinVer package into your projects, as per the [quick start](https://github.com/adamralph/minver#quick-start).

> I'm finding that I need to manually tag a build to get the right version at the moment.

For versions which you want to release, yes, that is how MinVer works. You tag, build, and then release.

**Comment by kieronlanning** [comment]
Thanks @adamralph - will that work with my shared `AssemblyInfo_Versioning.cs` file referenced above?

The versioning information is included using a `Directory.Build.props` so I don't need to include the same file in all projects. It happens automatically.

**Comment by adamralph** [comment]
@kieronlanning why do you have `AssemblyInfo_Versioning.cs`? Again, unless you're doing something exotic, you should be able to get rid of all that. The typical usage of MinVer is to just install it in your project(s) (using `Directory.Build.props` if preferred). You shouldn't have to do anything else involving `AssemblyInfo.cs`-type files, or passing any kind of versioning arguments around.

**Comment by kieronlanning** [comment]
@adamralph I guess I had it there because previously I'd used GitVersion to update that file prior to the build happening.

In my minds eye, I was trying to replicate that because it nicely separated the builds from versioning, plus there was zero dependencies within the solution/ projects as it was a Azure DevOps concern.

But I'll pull all that out, and try it with the package instead.

**Comment by adamralph** [comment]
@kieronlanning I'll close this now.

If you have more questions, please feel free to [start a discussion](https://github.com/adamralph/minver/discussions/new).
