### ISSUE TITLE
ability to limit scope of a project history

### ISSUE THREAD

**Issue by freddyrios** [adamralph/minver#500]
## Use case(s)

A base library for plugins as suggested [here](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support) is a project one would like to reduce the reasons to change. The main challenge with using MinVer with that is that any changes to the overall repository change the version. 

## Description

It would be great to be able to state the scope for the git history considered when generating the version. In the code of the min ver cli it runs: `"git log --pretty=format:"%H %P"`. When the feature is active, it could instead run `git log --pretty=format:"%H %P" projectFolder`.

By the way, while looking at the code I thought that maybe the working directory argument would do it, but it seems that only sets the working directory when running the command, instead of telling the command to be limited to that folder which is what I was looking for instead.

## Alternatives

Some alternatives are: 

- use separate repositories
- skip MinVer
- pretend the base library for plugins is defined in a separate repository and use separate solutions (or potentially just avoid having project references) + the prefix features

All these are cumbersome and confusing in the last case.

**Comment by freddyrios** [comment]
@adamralph that is what I mentioned in bullet 3 "pretend the base library for plugins is defined in a separate repository and use separate solutions (or potentially just avoid having project references) + the prefix features".

The problem with it forcing to treat the library as if it lived completely in a different repository is that one is forced to use a nuget reference instead of a project reference. That is cumbersome because every time one publishes updates to the independently versioned library one needs to manually update the reference with the corresponding version. It is confusing because someone not aware of this (or someone that just forgets over 1 year later) can easily miss updating the reference.

**Comment by adamralph** [comment]
But you will have that same problem regardless of whether you are using MinVer or not, no?

**Comment by freddyrios** [comment]
@adamralph if one manually versions the independent library in the csproj file then you get the right version each time. But that reintroduces the problem of any local builds across repositories being a pain (because of the version not changing with local commits).

If MinVer supported the alternative I suggest then it also does not happen. Why? because the version remains the same unless there are commits changing the project.

**Comment by adamralph** [comment]
So if I understand correctly, you want MinVer to produce one version in one project, and another version in another project. And the mechanism you are proposing for that is for an option to make MinVer look for tags only in a specific sub-folder of the repo. Is that correct?

**Comment by freddyrios** [comment]
@adamralph the problem is not tags but the prerelease version that gets generated. I would like MinVer to only consider commits in the sub-folder when determining the prerelease version. Note that passing the folder to git log returns only the commits that changed paths in that folder `git log --pretty=format:"%H %P" sub-folder`).

For example, if I have a folder "myproject", a min ver prefix called "myprefix" and a tag myprefix1.0.0, then the current version is already 1.0.0. Then a new commit comes that changes /unrelated/file.cs, but today that changes myproject's version to 1.0.1-alpha.0... and any projects depending on it get their dependency updated to >= that prerelease version. I would like it to stay at 1.0.0 in such case, while still allowing prereleases of myproject when a commit is made that changes /myproject/somefile.cs.

ps. I thought originally that Git.GetHeadOrDefault used the list of commits returned by git log as a simple list. I can see now that it keeps the parent links and Repository.GetVersion would probably get confused if it gets the list of commits filtered by the sub-folder / as often there would be parents that are not in the filtered output. One would probably need to keep the original list and the filtered by folders list / so as usual in software, more complex than it looks at first :D.

**Comment by adamralph** [comment]
@freddyrios thanks for the explanation, I understand what you mean now. I need to give it some more thought, and I'm re-opening while we discuss this.

**Comment by adamralph** [comment]
@freddyrios I had some more thoughts about this. I'm not sure there's any feature that could be added to MinVer for this, but I think you can acheive what you want using existing features.

Let's say you have two projects, `Main` and `Extension`, and `Extension 1.0.0` depends on `Main 1.0.0`. You then start working on `Extension 1.1.0`, and commit changes to that project. As I understand it, the problem you are facing is that, even though you are not committing to `Main`, that project starts to produce versions such as `Main 1.0.1-alpha.0.123` because of the changes your committing to `Extension`, even though you are not touching the `Main` project. You can solve this by "locking" `Main` to `1.0.0` by adding `<MinVerVersionOverride>1.0.0</MinVerVersionOverride>` to `Main.csproj`. Later, when you start committing changes to `Main`, you can "unlock" the version of `Main` by removing that property from `Main.csproj`.

**Comment by adamralph** [comment]
@freddyrios I'm going to close this as a `wontfix`, because I don't see a better path forward than what I suggested in my previous comment. If you have any further information, please let me know.
