### ISSUE TITLE
Let user disable version auto-increment

### ISSUE THREAD

**Issue by pomma89** [adamralph/minver#603]
## Use case(s)

Let's suppose that I tag a commit (`1.0.0`) and then I create two branches:

- Updates
- Preview

On the first one, I would apply dependencies updates and "cosmetic" fixes, such as improved documentation. I would like that the base version computed on that branch remained `1.0.0` because, after all, no notable changes have been applied. New commits would be versioned with `1.0.0-post.X`, for example.

On the second one, new features would be developed. Therefore, version auto-increment would be necessary and new commits would be versioned with `1.0.1-pre.X`, for example.

## Description

The desired use case can be mostly implemented using MinVer, except for the part where version is not incremented. I did not find how to do that, and I propose to add a new value, "none", to specify that no version part should be incremented.

```bash
dotnet minver --auto-increment none
```

I would be glad to try to open a PR, if this feature can be accepted.

## Alternatives

I did reason about this, but I did not find any valid alternative. Of course, I am open to suggestions.

## Additional context

None, sorry.

**Comment by adamralph** [comment]
@pomma89 thanks for raising this, but I'm afraid it doesn't make any sense.

> I would like that the base version computed on that branch remained `1.0.0` because, after all, no notable changes have been applied. New commits would be versioned with `1.0.0-post.X`, for example.

According to SemVer, `1.0.0-post.X` is a pre-release of `1.0.0`. It is an _earlier_ version than `1.0.0`. Any version _after_ `1.0.0` must increment at least one of the three dot-separated numbers, e.g. `1.0.1`, `1.1.0`, or `2.0.0`. Whether or not pre-release identifiers (a dash followed by something) are present doesn't change that.

**Comment by pomma89** [comment]
Thanks, @adamralph, for promptly answering this and for the explanation provided.

I understand what you are saying, and clearly what I wanted to do makes no sense.

Thanks again for the explanation 👍 

Goodbye,
Alessio
