### ISSUE TITLE
When work with Project to Project reference dependency is t

### ISSUE THREAD

**Issue by nsedoud** [adamralph/minver#605]
## Version(s)

2.5.0

## To reproduce

Steps to reproduce the behaviour:

1. create solution
2. add library project lib1
3. add an other library lib2 that reference lib1
4. all solution under git with no tag
5. commit

## Expected behaviour

the lib2.deps file should contains dependency to lib1/0.0.0-alpha.0 

## Actual behaviour

lib2.deps file contains dependency to lib1/1.0.0

**Comment by adamralph** [comment]
@nsedoud I followed the repro steps, and I can see that the `lib2.deps.json' file contains `"lib1/1.0.0"`,but I also see that `lib2.dll` correctly references `lib1, Version=0.0.0.0`, and if I create NuGet packages from the projects, I see that `lib2.0.0.0-alpha.0.nupkg` also correctly has a dependency on `lib1` version `0.0.0-alpha.0`.

So, while the `lib2.deps.json` file appears to contain incorrect information, does this actually cause any problems?

I have to admit, I have no idea what `deps.json` files are for.

**Comment by adamralph** [comment]
@nsedoud I'm closing this for now. If you can demonstrate why `lib2.deps.json` containing `"lib1/1.0.0"` is problematic, then please feel free to re-open this.

Moreover, I'm not sure this is avoidable. Although I don't understand the purpose of `deps.json` files, it seems like they are something created very early in the build process, when figuring out the versions of package dependencies. MinVer is a package, so it has to be restored and invoked before the versioning logic can happen. If my understanding is correct, then MinVer has not yet executed when the `deps.json` file is created. This means that `lib1` has the default version assigned by the SDK at the that time, which is `1.0.0`.

/cc @bording in case you can shed any more light.

**Comment by bording** [comment]
The `deps.json` files contain the information to resolve all the dependencies of the assembly at runtime. For a class library that doesn't have an entry point, that isn't going to matter at all.

Even if you add an .exe to the repro solution, the version in there still won't matter for the assemblies that come from project references. Those assemblies are copied into the bin folder, so they are loaded, and the info in the `deps.json` isn't referenced at all.

The main scenario for when the `deps.json` info would matter would be when you have a package reference dependency in your project, though that no longer matters either as of (IIRC) the .NET 3.1 SDK.

Before 3.1, a package reference assembly would not be copied to the bin folder of a project, so the `deps.json` info was used to find the correct assembly from the NuGet global packages folder on the system.

However, what happens now is that the relevant package reference assembly also gets copied into the bin folder, so for the most part I think the `deps.json` file is no longer used for anything.

As @adamralph pointed out, MinVer does [hook into the correct processes](https://github.com/adamralph/minver/blob/main/MinVer/build/MinVer.targets#L5) to ensure that the assembly references and package dependency versions are all correct, so it doesn't matter what the content of the `deps.json` file is.

**Comment by adamralph** [comment]
Thanks @bording. Great explanation as always.
