### ISSUE TITLE
Package version without preview suffix

### ISSUE THREAD

**Issue by WeihanLi** [adamralph/minver#714]
## Use case(s)

Hi, could we get a version without preview suffix? I want to use the version without suffix for a release.

I'm new here, I'm not sure if the feature already exists, I could not find it from the README

## Description

Get the calculated version without suffix

## Alternatives

Maybe we could parse it from the calculated version.

**Comment by adamralph** [comment]
please see my answers to https://github.com/adamralph/minver/discussions/703
