### ISSUE TITLE
CS7035 - The specified version string does not conform to the recommended format - major.minor.build.revision

### ISSUE THREAD

**Issue by viceice** [adamralph/minver#754]
## Version(s)

3.1.0

## To reproduce

Steps to reproduce the behaviour:

1. Add minver
2. Build with vs 2022
3. See warnings

## Expected behaviour

This warning shouldn't occure.

## Actual behaviour

A warning for every project and every target framework is shown
![image](https://user-images.githubusercontent.com/1798109/167584536-02ffb212-23ec-4606-a42f-3c441a9ae396.png)

## Workarounds

Suppress this error code

## Additional context

Seems somehow related to
- #342

**Comment by adamralph** [comment]
> Steps to reproduce the behaviour:
> 
> 1. Add minver
> 2. Build with vs 2022
> 3. See warnings

@viceice add MinVer to what?

More specifically, which project type and target framework? Which SDK version are you using?

**Comment by viceice** [comment]
Sorry, I've a big project with multiple classlibs and added minver to the git root `Directory.Build.props`.
The classlibs do have different target frameworks.
I'm using latest v6 sdk with vs 2022 professional.

**Comment by adamralph** [comment]
@viceice OK. Well, if I add MinVer 3.1.0 to `Directory.Build.props` for a new solution with two new class libraries, each targetting both `.netcoreapp3.1` and `net6.0`, using SDK 6.0.300 and VS 2022 17.2.0 (the latest versions of each), then I don't see the problem you are describing. I've pushed the test solution to https://github.com/adamralph/minver-754

I guess I will only be able to reproduce the problem if you provide me with either:

- Access to your solution, or
- Some other way to reproduce the problem

**Comment by viceice** [comment]
I'll try to create a minimal reproduction

**Comment by adamralph** [comment]
@viceice please feel free to reopen this if/when you can provide a way for me to reproduce the problem. Until then, I'll assume there is no bug.

**Comment by viceice** [comment]
sorry, no time for reproduction yet and the error seems to be gone. 🤷‍♂️ probably a temporary visual studio issue.
