### ISSUE TITLE
Fails on `osx-arm64`

### ISSUE THREAD

**Issue by lithiumtoast** [adamralph/minver#761]
## Version(s)

4.0

## To reproduce

```bash
$ dotnet tool install --global minver-cli                
You can invoke the tool using the following command: minver
Tool 'minver-cli' (version '4.0.0') was successfully installed.
$ minver
Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.19/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.19/libhostpolicy.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.19/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.19]
```

**Comment by adamralph** [comment]
@lithiumtoast thanks for reporting this, but I have no idea how to fix it. I don't have access to an ARM version of macOS. Do you have any ideas?

**Comment by adamralph** [comment]
According to https://docs.microsoft.com/en-us/answers/questions/471880/net-core-support-in-new-mac-os-arm-based-processor.html –

> .net 6 will be the first to produce a Mac arm image.

Would it be as simple as adding the `net6.0` TFM?

**Comment by adamralph** [comment]
@lithiumtoast I've released [4.1.0-alpha.1](https://www.nuget.org/packages/minver-cli/4.1.0-alpha.1) which contains a `net6.0` binary. Does it solve your problem?

**Comment by lithiumtoast** [comment]
https://www.nuget.org/packages/minver-cli/4.1.0-alpha.1 doesn't appear to be listed.

> Would it be as simple as adding the net6.0 TFM?

Yes using `net6.0` would the solution. I have a .NET 6 SDK installed for the RID `osx-arm64`.

**Comment by adamralph** [comment]
> https://www.nuget.org/packages/minver-cli/4.1.0-alpha.1 doesn't appear to be listed.

Yes, there appears to be a problem with pushing to NuGet right now. I'll respond again here when it is available.

**Comment by adamralph** [comment]
@lithiumtoast [4.1.0-alpha.1](https://www.nuget.org/packages/minver-cli/4.1.0-alpha.1) should now be available.

**Comment by lithiumtoast** [comment]
Yes it appears works now, thanks!

**Comment by adamralph** [comment]
@lithiumtoast great, thanks! Out of interest, does the regular [MinVer](https://www.nuget.org/packages/MinVer/4.0.0) package also work for you?

**Comment by adamralph** [comment]
(marking as `invalid` since this isn't a bug)
