### ISSUE TITLE
disable MinVerAutoIncrement

### ISSUE THREAD

**Issue by acquleo** [adamralph/minver#874]
In our organization we would like to have full control of version numbering.
Our jenkins system build will be only based on tags and don't want minver to automatically increment the following fields:
major-minor-patch

So I'm wondering if it is possible to add the option to disable MinVerAutoIncrement.

thanks

**Comment by adamralph** [comment]
I don't follow.

> Our jenkins system build will be only based on tags

So any version which you want to consume, tag it and build. You don't have to consume the interim auto-incremented versions.

**Comment by acquleo** [comment]
yes I know, i'd like to prevent that some developer to build a library using a release version that is not released yet.
But anyway I can manage this situation via internal guidelines.

thanks

**Comment by acquleo** [comment]
Is MinVerIgnoreHeight disable also the patch increment or not?
Just for information
Thanks
