### ISSUE TITLE
Auto increment patch part not working

### ISSUE THREAD

**Issue by nosalan** [adamralph/minver#948]
## Version(s)

4.3.0 cli

## To reproduce

The `-a` option (`--auto-increment`) does not seem to increment patch version. Works fine for minor and major:
![image](https://github.com/adamralph/minver/assets/2273250/a92acf01-d796-4df7-99e0-be77ef2b832a)

## Expected behaviour
Maybe I'm mistaken but I was expecting the `1-` to change to `2-` value. If this is expected then in which cases the `1-` will change? Also I'm curious hot to use only numeric approach `x.x.x` without the `-alpha` suffixes. Minver cli seems to always append it.

## Actual behaviour

Nothing changes in the output.

**Comment by adamralph** [comment]
The current behaviour is expected. `patch` is the default value of `--auto-increment`, so supplying no argument for `--auto-increment` is the same as supplying `patch`.

Regarding the general behaviour, I suggest you read about [how MinVer works](https://github.com/adamralph/minver#how-it-works). If you have a specific question, please open a [discussion](https://github.com/adamralph/minver/discussions/new/choose).

**Comment by nosalan** [comment]
Makes sense for me now, I was on a commit that was already tagged so it did not generate a new patch.
