### ISSUE TITLE
Tagged version wins even if MinVerMinimumMajorMinor is higher

### ISSUE THREAD

**Issue by DavidBoike** [adamralph/minver#999]
## Use case(s)

`MinVerMinimumMajorMinor` is provided as way to say: future dev work on this branch is for version x.y, rather than patches or minors on the previous version. It seems reasonable for someone to later decide that a commit on the branch is actually a patch or minor on the previous version, and tags the commit as such and expects that version to pop out.

## Description

As currently [stated by the docs](https://github.com/adamralph/minver?tab=readme-ov-file#how-it-works), "If the current commit has a version tag…The version is used as-is", without any mention of the `MinVerMinimumMajorMinor`. Described as a bug in https://github.com/adamralph/minver/issues/996 but this issue reframes the problem as a (breaking) enhancement.

## Alternatives

Leave it as is and change the docs to describe the actual behavior.

## Additional context

N/A

**Comment by bartelink** [comment]
So tempted to concoct a feature request right this instant :D
Except it would be more in the spirit of the project to suggest removing one...
Thanks for the amazing work in the last 999 items, Adam!

**Comment by adamralph** [comment]
@DavidBoike I've released this in [5.1.0-rc.1](https://www.nuget.org/packages/MinVer/5.1.0-rc.1)—please feel free to give it a try.

**Comment by adamralph** [comment]
re-released as [6.0.0-rc.1](https://www.nuget.org/packages/MinVer/6.0.0-rc.1) because the next release contains at least one breaking change
